apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shs-stage

images:
  - name: clemm.azurecr.io/ohifviewer/ohifviewer
    newTag: 1c89610678a99831e93475f9eb6da4758e1ff320
resources:
  - manifests.yaml