apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shs-stage

images:
  - name: clemm.azurecr.io/ohifviewer/ohifviewer
    newTag: a45f6d37c62d7f2cb308e27132e7d3d172a1e2fb
resources:
  - manifests.yaml